bakera/html-book

- md_text/3-7.md
Feature policy→Permissions Policy
> 3-7 iframe要素の更新

- md_text/3-4.md
> q要素のコード例を修正

- md_text/4-1.md
- md_text/4-4.md
> 4章のサンプルコード関連修正

- md_text/3-1.md
> meta=viewportの修正

- md_text/4-1.md
該当箇所についての提案PRです。
JavaScriptじゃなくて、あくまでHTMLの本だと思うと書きぶりの匙加減むずかしい･･･。サンプルコードとしては `forEach()` は戻りが `undefined` なので、`querySelectAll()` の戻りを `const menuButtonsList` に入れておくようにしてみました。
> 4-1：サンプルコードと説明の提案

- md_text/2-4.md
- md_text/2-7.md
- md_text/2-8.md
https://github.com/bakera/html-book/issues/156#issuecomment-963993367
２章にある JavaScript コードを #156 で固めた方針をもとに見直しました。
- 行末のセミコロンは省略しない
- リテラルはシングルクォートでくくる
- タブ幅は2タブ
> 2章の JavaScript コードを見直す

- md_text/2-6.md
- md_text/2-8.md
2-6の誤字の修正と、2-8のコード例のインデントの調整です。
> 2-6/2-8：誤字・コード例調整

- md_text/3-9-2.md
https://github.com/bakera/html-book/issues/156#issuecomment-963993367
３章で漏れがあった3-9-2における JavaScript コードを #156 で固めた方針をもとに見直しました。
> 3-9-2 の JavaScript コードを見直す

- .gitignore
すみません .gitignore がコミットされたことで私の手元がいろいろ面倒なことになってしまったので、手元で必要なものをpushさせてください。
> .gitignoreにいくつか追加

- epub_text/1-5.md
> fix #701 URLに/を追加

- epub_text/1-7.md
> fix #703 Markdown注釈に : を追加

- epub_text/2-8.md
> fix #712 ハイフンを追加

- epub_text/3-13.md
fix #725 
ついでにすぐ下の : の後ろにスペースがないのに気付いたので追加しています。
> fix #725 不要なテキストを削除

- epub_text/4-1.md
> fix #727 不要なバッククォートを削除

- epub_text/4-4.md
> fix #732 改行位置を修正

- epub_text/3-8.md
> fix #721 図版の位置を移動

- epub_text/3-2.md
> fix #713 「そのURL」→「特定のURL」

- epub_text/1-7.md
> fix #704 sを追加

- epub_text/2-3.md
> fix #671 キャプションを修正

- epub_text/4-4.md
> fix #657 テキスト調整
